version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appnet
    depends_on:
      - php
  php:
    image: jancyril/php:7.1-fpm
    volumes:
      - .:/var/www/html
    networks:
      - appnet
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - data:/var/lib/mysql
    networks:
      - appnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
